apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
spec:
  template:
    spec:
      containers:
        - name: balancereader
          envFrom:
            - secretRef:
                name: bank-app-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
spec:
  template:
    spec:
      containers:
        - name: ledgerwriter
          envFrom:
            - secretRef:
                name: bank-app-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionhistory
spec:
  template:
    spec:
      containers:
        - name: transactionhistory
          envFrom:
            - secretRef:
                name: bank-app-secrets
